const videoGames = [
    { id: 1, name: 'Final Fantasy VII', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 2, name: 'Final Fantasy VIII', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 3, name: 'Final Fantasy IX', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 4, name: 'Final Fantasy X', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 5, name: 'Final Fantasy XI', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 6, name: 'Final Fantasy XII', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 7, name: 'Final Fantasy XIII', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 8, name: 'Final Fantasy XIV', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 9, name: 'Final Fantasy XV', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 10, name: 'Final Fantasy Tactics', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 11, name: 'Final Fantasy Tactics: The War of the Lions', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 12, name: 'Final Fantasy Advance', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 13, name: 'Final Fantasy Tactics A2: Grimoire of the Rift', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }, { id: 14, name: 'Final Fantasy Crystal Chronicles', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }];

const boardGames = [
    { id: 1, name: 'Catan', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 2, name: 'Ticket to Ride', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 3, name: 'Pandemic', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 4, name: 'Codenames', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 5, name: 'Scrabble', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 6, name: 'Monopoly', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 7, name: 'Clue', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 8, name: 'Risk', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 9, name: 'Battleship', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 10, name: 'Sorry!', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 11, name: 'Chess', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 12, name: 'Checkers', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 13, name: 'Backgammon', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' },
    { id: 14, name: 'Go', description: 'The best game ever!', price: 100, inStock: true, isPopular: true, imgUrl: 'https://i.imgur.com/3J3wW9S.png' }];

module.exports = {
    videoGames, boardGames
};
